from dataclasses import dataclass


@dataclass(frozen=True)
class CropRule:
    crop_id: int
    name: str
    name_hindi: str
    season: str
    soil_ph_min: float
    soil_ph_max: float
    nitrogen_min: float
    nitrogen_max: float
    phosphorus_min: float
    phosphorus_max: float
    potassium_min: float
    potassium_max: float
    soil_moisture_min: float
    soil_moisture_max: float
    rainfall_min: float
    rainfall_max: float
    temperature_min: float
    temperature_max: float
    base_water_requirement: str
    base_market_demand: str
    base_duration: str
    default_investment: float
    default_profit_margin: float
    default_yield_range: str
    default_risk_level: str
    default_description: str


CROP_RULES: list[CropRule] = [
    CropRule(
        crop_id=101,
        name="Wheat",
        name_hindi="गेहूं",
        season="Rabi",
        soil_ph_min=6.0,
        soil_ph_max=7.5,
        nitrogen_min=40,
        nitrogen_max=90,
        phosphorus_min=30,
        phosphorus_max=70,
        potassium_min=30,
        potassium_max=80,
        soil_moisture_min=35,
        soil_moisture_max=70,
        rainfall_min=30,
        rainfall_max=120,
        temperature_min=10,
        temperature_max=25,
        base_water_requirement="Medium",
        base_market_demand="High",
        base_duration="110-130 days",
        default_investment=26000,
        default_profit_margin=62000,
        default_yield_range="20-26 quintal/acre",
        default_risk_level="Low",
        default_description="Suitable for well-drained loamy to alluvial soils during cooler growing windows.",
    ),
    CropRule(
        crop_id=102,
        name="Rice",
        name_hindi="धान",
        season="Kharif",
        soil_ph_min=5.0,
        soil_ph_max=7.5,
        nitrogen_min=50,
        nitrogen_max=100,
        phosphorus_min=25,
        phosphorus_max=70,
        potassium_min=35,
        potassium_max=90,
        soil_moisture_min=60,
        soil_moisture_max=95,
        rainfall_min=100,
        rainfall_max=300,
        temperature_min=20,
        temperature_max=35,
        base_water_requirement="High",
        base_market_demand="High",
        base_duration="110-150 days",
        default_investment=32000,
        default_profit_margin=58000,
        default_yield_range="18-28 quintal/acre",
        default_risk_level="Medium",
        default_description="Performs best in moisture-rich fields with warm temperatures and reliable rainfall.",
    ),
    CropRule(
        crop_id=103,
        name="Maize",
        name_hindi="मक्का",
        season="Kharif",
        soil_ph_min=5.5,
        soil_ph_max=7.5,
        nitrogen_min=45,
        nitrogen_max=100,
        phosphorus_min=25,
        phosphorus_max=70,
        potassium_min=25,
        potassium_max=80,
        soil_moisture_min=40,
        soil_moisture_max=75,
        rainfall_min=50,
        rainfall_max=150,
        temperature_min=18,
        temperature_max=32,
        base_water_requirement="Medium",
        base_market_demand="High",
        base_duration="95-120 days",
        default_investment=29000,
        default_profit_margin=70000,
        default_yield_range="22-32 quintal/acre",
        default_risk_level="Medium",
        default_description="A strong option for moderate rainfall zones with balanced fertility and warm weather.",
    ),
    CropRule(
        crop_id=104,
        name="Soybean",
        name_hindi="सोयाबीन",
        season="Kharif",
        soil_ph_min=6.0,
        soil_ph_max=7.5,
        nitrogen_min=25,
        nitrogen_max=70,
        phosphorus_min=25,
        phosphorus_max=70,
        potassium_min=30,
        potassium_max=80,
        soil_moisture_min=35,
        soil_moisture_max=70,
        rainfall_min=60,
        rainfall_max=150,
        temperature_min=20,
        temperature_max=32,
        base_water_requirement="Medium",
        base_market_demand="High",
        base_duration="95-115 days",
        default_investment=28000,
        default_profit_margin=50000,
        default_yield_range="14-19 quintal/acre",
        default_risk_level="Medium",
        default_description="Fits central Indian kharif conditions where drainage is good and rainfall is moderate.",
    ),
    CropRule(
        crop_id=105,
        name="Chickpea",
        name_hindi="चना",
        season="Rabi",
        soil_ph_min=6.0,
        soil_ph_max=8.0,
        nitrogen_min=20,
        nitrogen_max=60,
        phosphorus_min=20,
        phosphorus_max=65,
        potassium_min=20,
        potassium_max=70,
        soil_moisture_min=25,
        soil_moisture_max=55,
        rainfall_min=20,
        rainfall_max=80,
        temperature_min=12,
        temperature_max=28,
        base_water_requirement="Low",
        base_market_demand="High",
        base_duration="90-110 days",
        default_investment=21000,
        default_profit_margin=54000,
        default_yield_range="10-16 quintal/acre",
        default_risk_level="Low",
        default_description="A pulse crop suited to lower irrigation demand and cooler post-monsoon seasons.",
    ),
    CropRule(
        crop_id=106,
        name="Mustard",
        name_hindi="सरसों",
        season="Rabi",
        soil_ph_min=6.0,
        soil_ph_max=8.0,
        nitrogen_min=25,
        nitrogen_max=70,
        phosphorus_min=20,
        phosphorus_max=60,
        potassium_min=20,
        potassium_max=70,
        soil_moisture_min=20,
        soil_moisture_max=55,
        rainfall_min=20,
        rainfall_max=90,
        temperature_min=10,
        temperature_max=25,
        base_water_requirement="Low",
        base_market_demand="Medium",
        base_duration="85-105 days",
        default_investment=19000,
        default_profit_margin=47000,
        default_yield_range="12-18 quintal/acre",
        default_risk_level="Medium",
        default_description="Useful for farmers targeting an oilseed crop under low to moderate moisture conditions.",
    ),
    CropRule(
        crop_id=107,
        name="Cotton",
        name_hindi="कपास",
        season="Kharif",
        soil_ph_min=5.5,
        soil_ph_max=8.0,
        nitrogen_min=40,
        nitrogen_max=90,
        phosphorus_min=25,
        phosphorus_max=70,
        potassium_min=30,
        potassium_max=90,
        soil_moisture_min=30,
        soil_moisture_max=70,
        rainfall_min=50,
        rainfall_max=150,
        temperature_min=20,
        temperature_max=35,
        base_water_requirement="Medium",
        base_market_demand="High",
        base_duration="150-180 days",
        default_investment=36000,
        default_profit_margin=76000,
        default_yield_range="12-20 quintal/acre",
        default_risk_level="High",
        default_description="A long-duration cash crop best suited to warm climates with manageable pest pressure.",
    ),
    CropRule(
        crop_id=108,
        name="Groundnut",
        name_hindi="मूंगफली",
        season="Kharif",
        soil_ph_min=5.5,
        soil_ph_max=7.5,
        nitrogen_min=20,
        nitrogen_max=60,
        phosphorus_min=25,
        phosphorus_max=65,
        potassium_min=20,
        potassium_max=70,
        soil_moisture_min=30,
        soil_moisture_max=65,
        rainfall_min=50,
        rainfall_max=120,
        temperature_min=22,
        temperature_max=32,
        base_water_requirement="Medium",
        base_market_demand="Medium",
        base_duration="100-120 days",
        default_investment=24000,
        default_profit_margin=52000,
        default_yield_range="12-18 quintal/acre",
        default_risk_level="Medium",
        default_description="Works well in warm sandy-loam to loamy belts with moderate rainfall and drainage.",
    ),
]


def get_crop_rule(name: str) -> CropRule | None:
    normalized = name.strip().lower()
    for crop in CROP_RULES:
        if crop.name.lower() == normalized:
            return crop
    return None
